### ISSUE TITLE
dashboard无法读出数据BUG

### ISSUE THREAD

**Issue by airclear** [highso-fe/egg-exporter#10]
prometheus看指标已经有抓到了

![image](https://user-images.githubusercontent.com/4103690/159124655-b93d7daa-1a73-4e51-9a0f-65ba5500877d.png)

dashboard上啥数据都没有：

![image](https://user-images.githubusercontent.com/4103690/159124678-39d25c0a-a393-4efb-ac0d-d9127d1ee042.png)

**Comment by jianglin-wu** [comment]
已经合并请求
https://github.com/jianglin-wu/egg-exporter/pull/11
