### ISSUE TITLE
grafana 导入DataSource的时候，出现：HTTP Error Not Found

### ISSUE THREAD

**Issue by tangmengqiu** [highso-fe/egg-exporter#7]
首先在egg中开启了egg-exporter插件，在7000端口（grafana自己用的3000端口）
网页中打开：http://localhost:7000/metrics ，可以看到：
![image](https://user-images.githubusercontent.com/45224689/81493309-f1286d00-92d1-11ea-92bd-f935aa585fac.png)

然后grafana导入datasource:
![image](https://user-images.githubusercontent.com/45224689/81493316-06050080-92d2-11ea-850d-aeb10dd9a561.png)

最后出错：
![image](https://user-images.githubusercontent.com/45224689/81493326-14ebb300-92d2-11ea-95d1-2d4e5a648541.png)

**Comment by tangmengqiu** [comment]
grafana中的日志是：connection refuse。

**Comment by jianglin-wu** [comment]
`http://localhost:7000/metrics` 暴露的指标信息需要通过 Prometheus 定时拉取数据存储在时序数据库，然后通过 Grafana 从时序数据库中查询数据展示到看板上。所以，你需要部署一个 Prometheus。
